import csv

c704273 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "選修",
  "reqSelENa": "Elective",
  "reqSel": "S",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "助理教授",
  "titleENa": "Assistant Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中文",
  "teaLangENa": "Chinese",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "需自帶筆電上課",
  "seqList": [
    "Monday 星期一/D5,D6,D7/SF130"
  ],
  "rejList": [],
  "tchList": [
    "韓千山(專任/副教授)"
  ],
  "jonCouSn": 704273,
  "hy": 112,
  "ht": 1,
  "avaNO": "D0F0333541",
  "couCNa": "金融數據分析與智慧交易",
  "couENa": "Financial data Analysis and Intelligent Trading",
  "tchNo": "072214",
  "tchCNa": "邱嘉洲",
  "tchENa": "CHIU, CHIA-CHOU",
  "teaMain": "Y",
}
c700310 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "選修",
  "reqSelENa": "Elective",
  "reqSel": "S",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "助理教授",
  "titleENa": "Assistant Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中文",
  "teaLangENa": "Chinese",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "",
  "seqList": [
    "Monday 星期一/E1,E2,E3/LW210"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 700310,
  "hy": 112,
  "ht": 1,
  "avaNO": "G745032133",
  "couCNa": "敏捷式軟體開發",
  "couENa": "Agile Software Development",
  "tchNo": "053792",
  "tchCNa": "吳濟聰",
  "tchENa": "WU, JI-TSUNG",
  "teaMain": "Y",
}
c700318 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "選修",
  "reqSelENa": "Elective",
  "reqSel": "S",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "教授",
  "titleENa": "Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中文",
  "teaLangENa": "Chinese",
  "teaMaterCNa": "中文",
  "teaMaterENa": "Chinese",
  "avaNote": "",
  "seqList": [
    "Friday 星期五/E1,E2,E3/LW210"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 700318,
  "hy": 112,
  "ht": 1,
  "avaNO": "G745034637",
  "couCNa": "醫療健康大數據分析與應用",
  "couENa": "Big Data Analytics in Medical and Healthcare",
  "tchNo": "059099",
  "tchCNa": "呂奇傑",
  "tchENa": "LU, CHI-JIE",
  "teaMain": "Y",
}
c693891 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "必修",
  "reqSelENa": "Required",
  "reqSel": "R",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "副教授",
  "titleENa": "Associate Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中英文",
  "teaLangENa": "Chinese & English",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "",
  "seqList": [
    "Friday 星期五/D2,D3,D4/LW210"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 693891,
  "hy": 112,
  "ht": 1,
  "avaNO": "G746107939",
  "couCNa": "高等資料庫管理",
  "couENa": "Advanced Database Management",
  "tchNo": "013477",
  "tchCNa": "蔡幸蓁",
  "tchENa": "TSAI, HSINE-JEN",
  "teaMain": "Y",
}
c693892 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "必修",
  "reqSelENa": "Required",
  "reqSel": "R",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "教授",
  "titleENa": "Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中英文",
  "teaLangENa": "Chinese & English",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "電子商務學群必修",
  "seqList": [
    "Thursday 星期四/D2,D3,D4/LW210"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 693892,
  "hy": 112,
  "ht": 1,
  "avaNO": "G746109290",
  "couCNa": "電子商務總論",
  "couENa": "General Topics on Electronic Commerce",
  "tchNo": "052122",
  "tchCNa": "廖建翔",
  "tchENa": "LIAO, CHIEN-HSIANG",
  "teaMain": "Y",
}
c704276 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "選修",
  "reqSelENa": "Elective",
  "reqSel": "S",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "校聘助理教授級專案教學人員",
  "titleENa": "Contracted Assistant Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中文",
  "teaLangENa": "Chinese",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "",
  "seqList": [
    "Monday 星期一/D5,D6,D7/SF339"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 704276,
  "hy": 112,
  "ht": 1,
  "avaNO": "G746110849",
  "couCNa": "知識管理",
  "couENa": "Knowledge Management",
  "tchNo": "154327",
  "tchCNa": "林雅文",
  "tchENa": "Ya-Wen Lin",
  "teaMain": "Y",
}
c693893 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "必修",
  "reqSelENa": "Required",
  "reqSel": "R",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "教授",
  "titleENa": "Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中英文",
  "teaLangENa": "Chinese & English",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "人工智慧學群5選3必修",
  "seqList": [
    "Thursday 星期四/D5,D6,D7/LW210"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 693893,
  "hy": 112,
  "ht": 1,
  "avaNO": "G746113027",
  "couCNa": "機器學習",
  "couENa": "Machine Learning",
  "tchNo": "059099",
  "tchCNa": "呂奇傑",
  "tchENa": "LU, CHI-JIE",
  "teaMain": "Y",
}
c693894 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "必修",
  "reqSelENa": "Required",
  "reqSel": "R",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "助理教授",
  "titleENa": "Assistant Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中英文",
  "teaLangENa": "Chinese & English",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "須參加週二D3-D4資訊管理講座課程演講活動",
  "seqList": [
    "Monday 星期一/D2,D3,D4/LW210"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 693894,
  "hy": 112,
  "ht": 1,
  "avaNO": "G746116910",
  "couCNa": "高等資訊管理",
  "couENa": "Advanced Information Management",
  "tchNo": "146414",
  "tchCNa": "林湘霖",
  "tchENa": "LIN, SHIANG LIN",
  "teaMain": "Y",
}
c693895 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "必修",
  "reqSelENa": "Required",
  "reqSel": "R",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "副教授",
  "titleENa": "Associate Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中文",
  "teaLangENa": "Chinese",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "電子商務學群5選3必修",
  "seqList": [
    "Friday 星期五/D5,D6,D7/LW210"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 693895,
  "hy": 112,
  "ht": 1,
  "avaNO": "G746123666",
  "couCNa": "網路行銷專題",
  "couENa": "Special Topics on Internet Marketing",
  "tchNo": "042833",
  "tchCNa": "張銀益",
  "tchENa": "CHANG, YIN-YIH",
  "teaMain": "Y",
}
c700270 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "選修",
  "reqSelENa": "Elective",
  "reqSel": "S",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "助理教授",
  "titleENa": "Assistant Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中英文",
  "teaLangENa": "Chinese & English",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "",
  "seqList": [
    "Thursday 星期四/E1,E2,E3/LW210"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 700270,
  "hy": 112,
  "ht": 1,
  "avaNO": "G746124103",
  "couCNa": "決策分析",
  "couENa": "Decision Analysis",
  "tchNo": "146414",
  "tchCNa": "林湘霖",
  "tchENa": "LIN, SHIANG LIN",
  "teaMain": "Y",
}
c693897 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "選修",
  "reqSelENa": "Elective",
  "reqSel": "S",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "教授",
  "titleENa": "Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中文",
  "teaLangENa": "Chinese",
  "teaMaterCNa": "中文",
  "teaMaterENa": "Chinese",
  "avaNote": "",
  "seqList": [
    "Wednesday 星期三/D2,D3,D4/LW210"
  ],
  "rejList": [],
  "tchList": [
    "葉承達(專任/教授)"
  ],
  "jonCouSn": 693897,
  "hy": 112,
  "ht": 1,
  "avaNO": "G746132135",
  "couCNa": "人工智慧產業實務",
  "couENa": "Industry Practices in Artificial Intelligence",
  "tchNo": "140485",
  "tchCNa": "黃曜輝",
  "tchENa": "Yao-Huei Huang",
  "teaMain": "Y",
}
c693898 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "必修",
  "reqSelENa": "Required",
  "reqSel": "R",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "校聘助理教授級專案教學人員",
  "titleENa": "Contracted Assistant Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中英文",
  "teaLangENa": "Chinese & English",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "人工智慧學群5選3必修、電子商務學群5選3必修",
  "seqList": [
    "Tuesday 星期二/D5,D6,D7/LW210"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 693898,
  "hy": 112,
  "ht": 1,
  "avaNO": "G746133034",
  "couCNa": "物聯網概論與應用",
  "couENa": "Internet of Things",
  "tchNo": "155360",
  "tchCNa": "林青峰",
  "tchENa": "Qing-Feng Lin",
  "teaMain": "Y",
}
c693900 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩二",
  "dptGrdEng": "Information Management (Master's Program Year Two)",
  "reqSelCNa": "必修",
  "reqSelENa": "Required",
  "reqSel": "R",
  "term": 0,
  "credit": 1,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "教授",
  "titleENa": "Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中文",
  "teaLangENa": "Chinese",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "請碩一同學也全程參與聽講",
  "seqList": [
    "Tuesday 星期二/D3,D4/LW210"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 693900,
  "hy": 112,
  "ht": 1,
  "avaNO": "G746216654",
  "couCNa": "資訊管理講座",
  "couENa": "Seminar on Information Management",
  "tchNo": "076144",
  "tchCNa": "董惟鳳",
  "tchENa": "TUNG, WEI-FENG",
  "teaMain": "Y",
}

c668045 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "選修",
  "reqSelENa": "Elective",
  "reqSel": "S",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "校聘助理教授級專案教學人員",
  "titleENa": "Contracted Assistant Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中文",
  "teaLangENa": "Chinese",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "需自帶筆電上課",
  "seqList": [
    "Thursday 星期四/D5,D6,D7/SF339"
  ],
  "rejList": [],
  "tchList": [
    "韓千山(專任/副教授)"
  ],
  "jonCouSn": 668045,
  "hy": 111,
  "ht": 2,
  "avaNO": "D0F0333540",
  "couCNa": "金融程式應用",
  "couENa": "Financial Programming Application",
  "tchNo": "155447",
  "tchCNa": "胡聚男",
  "tchENa": "HU, CHU NAN",
  "teaMain": "Y",
}
c668042 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "選修",
  "reqSelENa": "Elective",
  "reqSel": "S",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "教授",
  "titleENa": "Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中文",
  "teaLangENa": "Chinese",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "",
  "seqList": [
    "Thursday 星期四/E1,E2,E3/LW210"
  ],
  "rejList": [],
  "tchList": [
    "呂奇傑(專任/教授)"
  ],
  "jonCouSn": 668042,
  "hy": 111,
  "ht": 2,
  "avaNO": "G745032134",
  "couCNa": "深度學習導論與應用",
  "couENa": "Deep Learning and its Applications",
  "tchNo": "140485",
  "tchCNa": "黃曜輝",
  "tchENa": "Yao-Huei Huang",
  "teaMain": "Y",
}
c668047 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "選修",
  "reqSelENa": "Elective",
  "reqSel": "S",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "助理教授",
  "titleENa": "Assistant Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中文",
  "teaLangENa": "Chinese",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "",
  "seqList": [
    "Wednesday 星期三/E1,E2,E3/LW210"
  ],
  "rejList": [],
  "tchList": [
    "董惟鳳(專任/教授)"
  ],
  "jonCouSn": 668047,
  "hy": 111,
  "ht": 2,
  "avaNO": "G745033856",
  "couCNa": "使用者經驗設計",
  "couENa": "User Experience Design",
  "tchNo": "053792",
  "tchCNa": "吳濟聰",
  "tchENa": "WU, JI-TSUNG",
  "teaMain": "Y",
}
c667946 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "必修",
  "reqSelENa": "Required",
  "reqSel": "R",
  "term": 0,
  "credit": 2,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "副教授",
  "titleENa": "Associate Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中文",
  "teaLangENa": "Chinese",
  "teaMaterCNa": "中文",
  "teaMaterENa": "Chinese",
  "avaNote": "",
  "seqList": [
    "Wednesday 星期三/D3,D4/LM510"
  ],
  "rejList": [],
  "tchList": [
    "魏嘉華(兼任/副教授)",
    "李禮孟(專任/副教授)"
  ],
  "jonCouSn": 667946,
  "hy": 111,
  "ht": 2,
  "avaNO": "G746100292",
  "couCNa": "企業倫理",
  "couENa": "Business Ethics",
  "tchNo": "070788",
  "tchCNa": "聶達安",
  "tchENa": "NIEWDANA, LESZEK",
  "teaMain": "Y",
}
c667949 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "必修",
  "reqSelENa": "Required",
  "reqSel": "R",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "教授",
  "titleENa": "Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中英文",
  "teaLangENa": "Chinese & English",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "人工智慧學群5選3必修",
  "seqList": [
    "Tuesday 星期二/D5,D6,D7/LW210"
  ],
  "rejList": [],
  "tchList": [
    "葉承達(專任/教授)"
  ],
  "jonCouSn": 667949,
  "hy": 111,
  "ht": 2,
  "avaNO": "G746101016",
  "couCNa": "人工智慧",
  "couENa": "Artificial Intelligence",
  "tchNo": "059099",
  "tchCNa": "呂奇傑",
  "tchENa": "LU, CHI-JIE",
  "teaMain": "Y",
}
c667952 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "必修",
  "reqSelENa": "Required",
  "reqSel": "R",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "教授",
  "titleENa": "Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中英文",
  "teaLangENa": "Chinese & English",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "電子商務學群5選3必修",
  "seqList": [
    "Friday 星期五/D2,D3,D4/LW210"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 667952,
  "hy": 111,
  "ht": 2,
  "avaNO": "G746101799",
  "couCNa": "研究方法",
  "couENa": "Research Methodology",
  "tchNo": "052122",
  "tchCNa": "廖建翔",
  "tchENa": "LIAO, CHIEN-HSIANG",
  "teaMain": "Y",
}
c667998 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "選修",
  "reqSelENa": "Elective",
  "reqSel": "S",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "校聘助理教授級專案教學人員",
  "titleENa": "Contracted Assistant Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中文",
  "teaLangENa": "Chinese",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "",
  "seqList": [
    "Monday 星期一/D5,D6,D7/SF339"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 667998,
  "hy": 111,
  "ht": 2,
  "avaNO": "G746110849",
  "couCNa": "知識管理",
  "couENa": "Knowledge Management",
  "tchNo": "154327",
  "tchCNa": "林雅文",
  "tchENa": "Ya-Wen Lin",
  "teaMain": "Y",
}
c668028 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "必修",
  "reqSelENa": "Required",
  "reqSel": "R",
  "term": 0,
  "credit": 2,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "副教授",
  "titleENa": "Associate Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中文",
  "teaLangENa": "Chinese",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "電子商務學群5選3必修",
  "seqList": [
    "Friday 星期五/D5,D6/LW210"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 668028,
  "hy": 111,
  "ht": 2,
  "avaNO": "G746123668",
  "couCNa": "電子採購與物流專題",
  "couENa": "Special Tops on Electronic Procurement and Logistic",
  "tchNo": "042833",
  "tchCNa": "張銀益",
  "tchENa": "CHANG, YIN-YIH",
  "teaMain": "Y",
}
c668034 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "選修",
  "reqSelENa": "Elective",
  "reqSel": "S",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "副教授",
  "titleENa": "Associate Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中文",
  "teaLangENa": "Chinese",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": "",
  "seqList": [
    "Thursday 星期四/D2,D3,D4/LW210"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 668034,
  "hy": 111,
  "ht": 2,
  "avaNO": "G746131354",
  "couCNa": "行動式雲端服務應用設計",
  "couENa": "Mobile Cloud Service Applications Design",
  "tchNo": "013459",
  "tchCNa": "劉富容",
  "tchENa": "LIU, FU-JUNG",
  "teaMain": "Y",
}
c688189 = {
  "dayCNa": "研究所",
  "dayENa": "Graduate Programs",
  "dptGrdCN": "資管碩一",
  "dptGrdEng": "Information Management (Master's Program Year One)",
  "reqSelCNa": "必修",
  "reqSelENa": "Required",
  "reqSel": "R",
  "term": 0,
  "credit": 3,
  "sideCNa": "專任",
  "sideENa": "Full-time",
  "titleCNa": "教授",
  "titleENa": "Professor",
  "teaSkill": "Y",
  "teaLangCNa": "中英文",
  "teaLangENa": "Chinese & English",
  "teaMaterCNa": "中英文",
  "teaMaterENa": "Chinese & English",
  "avaNote": " 電子商務學群5選3必修課",
  "seqList": [
    "Tuesday 星期二/D2,D3,D4/LW210"
  ],
  "rejList": [],
  "tchList": [],
  "jonCouSn": 688189,
  "hy": 111,
  "ht": 2,
  "avaNO": "G746135555",
  "couCNa": "金融科技與金融行銷",
  "couENa": "none",
  "tchNo": "157287",
  "tchCNa": "許嘉霖",
  "tchENa": "無",
  "teaMain": "Y",
}

courses = [c704273,c700310,c700318,c693891,c693892,c704276,c693893,c693894,c693895,c700270,c693897,c693898,c693900,c668045,c668042,c668047,c667946,c667949,c667952,c667998,c668028,c668034,c688189]
# course = [c704273]
data = [
        ['學制別','學年度','學期','開課單位','課程編號','科目名稱','上課日','上課時間','上課地點','選別','學分','教師背景','教師職稱','授課教師','授課語言'],
    ]
for i in courses:
    div = i["dayCNa"]
    year = i["hy"]
    sem = i["ht"]
    dept = i["dptGrdCN"]
    course_num = i["avaNO"]
    course_title = i["couCNa"]
    seqList = i["seqList"][0].split('/')
    day = seqList[0]
    time = seqList[1]
    ven = seqList[2]
    compul = i["reqSelCNa"]
    cred = i["credit"]
    tch_bg = i["sideCNa"]
    tch_title = i["titleCNa"]
    tch_name = i["tchCNa"]
    lang = i["teaLangCNa"]
    # print(div, year, sem, dept, course_num, course_title, day, time, ven, compul, cred, tch_bg, tch_title, tch_name, lang)
    data.append([div, year, sem, dept, course_num, course_title, day, time, ven, compul, cred, tch_bg, tch_title, tch_name, lang])
# print(data)
with open('data.csv', 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(data[0])
    writer.writerows(data[1:])
    csvfile.close()



